### ISSUE TITLE
Controller continuously crashLoop during WGE upgrade

### ISSUE THREAD

**Issue by souleb** [weaveworks/gitopssets-controller#122]
After upgrading Flux to v2.1.0 we have tried upgrading WGE, but the gitopssets controller keeps crash Looping.

We use the following HelmRlease:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops-enterprise-charts
  namespace: flux-system
spec:
  interval: 10m
  secretRef:
    name: xxx
  url: https://charts.dev.wkp.weave.works/releases/charts-v3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-enterprise
  namespace: flux-system
spec:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: mccp
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-enterprise-charts
        namespace: flux-system
      version: 0.30.0
  interval: 10m
  values:
    enableExplorer: true
    enableTerraformUI: true
    global:
      capiEnabled: false
    # -- Configure TLS settings if needed
    tls:
      enabled: false
    config:
      capi:
        repositoryURL: xxx
        # -- Can be changed depending on your git repo structure
        repositoryPath: ./clusters/empcentral-dv-aks/clusters
        # repositoryClustersPath: ./cluster
      git:
        type: github
        # -- Change if using on-prem github/gitlab
        # hostname: https://github.com
      oidc:
        enabled: true
        issuerURL: xxx
        redirectURL: xxx
        clientCredentialsSecret: xxx
      auth:
        userAccount:
          enabled: false
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        external-dns.alpha.kubernetes.io/target: xxx
      hosts:
        - host: xxx
          paths:
            - path: /
              pathType: ImplementationSpecific
    gitopssets-controller:
      controllerManager:
        manager:
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
            - --enabled-generators=GitRepository,Cluster,PullRequests,List,APIClient,ImagePolicy,Matrix,Config
 ```

We use Azure AKS with the following cluster info
```json
{
  "major": "1",
  "minor": "25",
  "gitVersion": "v1.25.11",
  "gitCommit": "8cfcba0b15c343a8dc48567a74c29ec4844e0b9e",
  "gitTreeState": "clean",
  "buildDate": "2023-06-19T16:12:25Z",
  "goVersion": "go1.19.10",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

Flux version returns :
```sh
⋊> ~ flux version                                                                                                                                                                                   10:42:12
flux: v2.1.0
helm-controller: v0.36.0
image-automation-controller: v0.36.0
image-reflector-controller: v0.30.0
kustomize-controller: v1.1.0
notification-controller: v1.1.0
source-controller: v1.1.0
```
